# Generated by Django 4.2.9 on 2024-08-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('сan_block_user', 'Сan block user')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
