# Generated by Django 5.0.7 on 2024-07-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Введите дату и время первой отправки рассылки', verbose_name='Дата и время первой отправки рассылки')),
                ('end_datetime', models.DateTimeField(help_text='Введите дату и время окончания рассылки', verbose_name='Дата и время окончания рассылки')),
                ('periodicity', models.CharField(choices=[('once a day', 'раз в день'), ('once a week', 'раз в неделю'), ('once a month', 'раз в месяц')], default='раз в день', help_text='Выберите периодичность рассылки', verbose_name='Периодичность рассылки')),
                ('mailing_status', models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена')], default='создана', help_text='Выберите статус рассылки', verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(help_text='Выберите клиентов для рассылки', related_name='client_of', to='mailing.client', verbose_name='Клиенты для рассылки')),
                ('message', models.ForeignKey(help_text='Выберите сообщение для рассылки', on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Настройки рассылки',
                'verbose_name_plural': 'Настройки рассылок',
            },
        ),
    ]
