# Generated by Django 5.0.7 on 2024-07-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_last_try', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки рассылки')),
                ('attempt_status', models.CharField(choices=[('Successfully', 'Успешно'), ('Not successful', 'Не успешно')], default=None, verbose_name='Статус попытки рассылки')),
                ('response_mail_server', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
            },
        ),
    ]
