# Generated by Django 4.2.9 on 2024-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_client_owner_mailingsettings_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'ordering': ['-id'], 'permissions': [('сan_disable_mailings', 'Сan disable mailings')], 'verbose_name': 'Настройки рассылки', 'verbose_name_plural': 'Настройки рассылок'},
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='is_disabled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отключена менеджером'),
        ),
    ]
