# Generated by Django 4.2.9 on 2024-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailingsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='datetime_last_try',
            field=models.DateTimeField(verbose_name='Дата и время последней попытки рассылки'),
        ),
    ]
