# Generated by Django 4.2.9 on 2024-08-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailingattempt_datetime_last_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_status',
            field=models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена')], default='created', help_text='Выберите статус рассылки', verbose_name='Статус рассылки'),
        ),
    ]
